# Form implementation generated from reading ui file 'd:\XavierUI\simple.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1004, 969)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(0, 0, 1001, 161))
        self.groupBox.setStyleSheet("QGroupBox {\n"
"    background-color: #003087; /* Xavier blue */\n"
"}\n"
"QGroupBox {\n"
"    background-color: #003087;\n"
"    border: 2px solid #FFD700; /* Xavier gold border */\n"
"}\n"
"QGroupBox {\n"
"    background-color: #003087;\n"
"    border: 2px solid #FFD700;\n"
"    border-radius: 5px;\n"
"    color: white;\n"
"}")
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(parent=self.groupBox)
        self.label.setGeometry(QtCore.QRect(40, 10, 171, 141))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("C:/Users/jhora/Downloads/XU_logo_type_ver_2.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(550, 60, 31, 31))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("C:/Users/jhora/Downloads/2023_Facebook_icon.svg.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(600, 60, 41, 31))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("C:/Users/jhora/Downloads/Logo_of_Twitter.svg.webp"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(660, 60, 31, 31))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("C:/Users/jhora/Downloads/images (1).jpg"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.textBrowser = QtWidgets.QTextBrowser(parent=self.groupBox)
        self.textBrowser.setGeometry(QtCore.QRect(720, 60, 151, 31))
        self.textBrowser.setObjectName("textBrowser")
        self.groupBox_2 = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(0, 160, 1001, 51))
        self.groupBox_2.setStyleSheet("QGroupBox {\n"
"    background-color: #FFE28E\n"
"}")
        self.groupBox_2.setObjectName("groupBox_2")
        self.toolButton = QtWidgets.QToolButton(parent=self.groupBox_2)
        self.toolButton.setGeometry(QtCore.QRect(30, 20, 51, 19))
        self.toolButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.toolButton.setAcceptDrops(True)
        self.toolButton.setCheckable(False)
        self.toolButton.setObjectName("toolButton")
        self.toolButton_2 = QtWidgets.QToolButton(parent=self.groupBox_2)
        self.toolButton_2.setGeometry(QtCore.QRect(110, 20, 61, 19))
        self.toolButton_2.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.toolButton_2.setAcceptDrops(True)
        self.toolButton_2.setCheckable(False)
        self.toolButton_2.setObjectName("toolButton_2")
        self.toolButton_3 = QtWidgets.QToolButton(parent=self.groupBox_2)
        self.toolButton_3.setGeometry(QtCore.QRect(200, 20, 101, 19))
        self.toolButton_3.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.toolButton_3.setAcceptDrops(True)
        self.toolButton_3.setCheckable(False)
        self.toolButton_3.setObjectName("toolButton_3")
        self.toolButton_4 = QtWidgets.QToolButton(parent=self.groupBox_2)
        self.toolButton_4.setGeometry(QtCore.QRect(330, 20, 71, 19))
        self.toolButton_4.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.toolButton_4.setAcceptDrops(True)
        self.toolButton_4.setCheckable(False)
        self.toolButton_4.setObjectName("toolButton_4")
        self.toolButton_5 = QtWidgets.QToolButton(parent=self.groupBox_2)
        self.toolButton_5.setGeometry(QtCore.QRect(430, 20, 61, 19))
        self.toolButton_5.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.toolButton_5.setAcceptDrops(True)
        self.toolButton_5.setCheckable(False)
        self.toolButton_5.setObjectName("toolButton_5")
        self.toolButton_6 = QtWidgets.QToolButton(parent=self.groupBox_2)
        self.toolButton_6.setGeometry(QtCore.QRect(520, 20, 71, 19))
        self.toolButton_6.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.toolButton_6.setAcceptDrops(True)
        self.toolButton_6.setCheckable(False)
        self.toolButton_6.setObjectName("toolButton_6")
        self.toolButton_7 = QtWidgets.QToolButton(parent=self.groupBox_2)
        self.toolButton_7.setGeometry(QtCore.QRect(620, 20, 61, 19))
        self.toolButton_7.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.toolButton_7.setAcceptDrops(True)
        self.toolButton_7.setCheckable(False)
        self.toolButton_7.setObjectName("toolButton_7")
        self.toolButton_8 = QtWidgets.QToolButton(parent=self.groupBox_2)
        self.toolButton_8.setGeometry(QtCore.QRect(710, 20, 91, 19))
        self.toolButton_8.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.toolButton_8.setAcceptDrops(True)
        self.toolButton_8.setCheckable(False)
        self.toolButton_8.setObjectName("toolButton_8")
        self.toolButton_9 = QtWidgets.QToolButton(parent=self.groupBox_2)
        self.toolButton_9.setGeometry(QtCore.QRect(840, 20, 61, 19))
        self.toolButton_9.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.toolButton_9.setAcceptDrops(True)
        self.toolButton_9.setCheckable(False)
        self.toolButton_9.setObjectName("toolButton_9")
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(-10, 210, 1011, 281))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("C:/Users/jhora/Downloads/09242024.Web.Banner_-_XU_Autonomous_Status_-_Website_Banner.jpg"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.groupBox_3 = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(0, 490, 1001, 461))
        self.groupBox_3.setStyleSheet("QGroupBox {\n"
"    background-color: #D3D3D3\n"
"}")
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_6 = QtWidgets.QLabel(parent=self.groupBox_3)
        self.label_6.setGeometry(QtCore.QRect(390, 0, 211, 41))
        self.label_6.setStyleSheet("QLabel {\n"
"    font-family: \"Times New Roman\";\n"
"    font-size: 16pt; /* Adjust size as needed */\n"
"    color: #003087; /* Xavier University blue */\n"
"}")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(parent=self.groupBox_3)
        self.label_7.setGeometry(QtCore.QRect(680, 50, 241, 141))
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap("C:/Users/jhora/Downloads/ba3b4e33a2dd3e25a3b805da4cdcf437-01182025.Web.Thumbnail_-_Kinaiyahan_-_spotlight_thumbnail_-_1_Dec_2024.jpg"))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(parent=self.groupBox_3)
        self.label_8.setGeometry(QtCore.QRect(370, 50, 241, 141))
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap("C:/Users/jhora/Downloads/f1df0d00b74efa9c8f9dcc358b0bc1b2-05242023.Web.DSC05387.jpg"))
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(parent=self.groupBox_3)
        self.label_9.setGeometry(QtCore.QRect(50, 50, 241, 141))
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap("C:/Users/jhora/Downloads/393681259c802828922a8497adf5bb03-05252024.Web_-_New_CampusThumbnail.jpg"))
        self.label_9.setScaledContents(True)
        self.label_9.setObjectName("label_9")
        self.label_12 = QtWidgets.QLabel(parent=self.groupBox_3)
        self.label_12.setGeometry(QtCore.QRect(40, 200, 211, 41))
        self.label_12.setStyleSheet("QLabel {\n"
"    font-family: \"Times New Roman\";\n"
"    font-size: 16pt; /* Adjust size as needed */\n"
"    color: #003087; /* Xavier University blue */\n"
"}")
        self.label_12.setText("")
        self.label_12.setObjectName("label_12")
        self.label_10 = QtWidgets.QLabel(parent=self.groupBox_3)
        self.label_10.setGeometry(QtCore.QRect(50, 200, 251, 21))
        self.label_10.setStyleSheet("QLabel {\n"
"    font-family: \"Times New Roman\";\n"
"    font-size: 8pt;\n"
"    font-weight: bold;\n"
"    color: #003087;\n"
"}")
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(parent=self.groupBox_3)
        self.label_11.setGeometry(QtCore.QRect(80, 220, 191, 21))
        self.label_11.setStyleSheet("QLabel {\n"
"    font-family: \"Times New Roman\";\n"
"    font-size: 8pt;\n"
"    font-weight: bold;\n"
"    color: #003087;\n"
"}")
        self.label_11.setObjectName("label_11")
        self.label_13 = QtWidgets.QLabel(parent=self.groupBox_3)
        self.label_13.setGeometry(QtCore.QRect(90, 240, 161, 21))
        self.label_13.setStyleSheet("QLabel {\n"
"    font-family: \"Times New Roman\";\n"
"    font-size: 8pt;\n"
"    font-weight: bold;\n"
"    color: #003087;\n"
"}")
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(parent=self.groupBox_3)
        self.label_14.setGeometry(QtCore.QRect(350, 200, 281, 21))
        self.label_14.setStyleSheet("QLabel {\n"
"    font-family: \"Times New Roman\";\n"
"    font-size: 8pt;\n"
"    font-weight: bold;\n"
"    color: #003087;\n"
"}")
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(parent=self.groupBox_3)
        self.label_15.setGeometry(QtCore.QRect(680, 200, 251, 21))
        self.label_15.setStyleSheet("QLabel {\n"
"    font-family: \"Times New Roman\";\n"
"    font-size: 8pt;\n"
"    font-weight: bold;\n"
"    color: #003087;\n"
"}")
        self.label_15.setObjectName("label_15")
        self.groupBox_4 = QtWidgets.QGroupBox(parent=self.groupBox_3)
        self.groupBox_4.setGeometry(QtCore.QRect(-10, 270, 1001, 181))
        self.groupBox_4.setStyleSheet("QGroupBox {\n"
"    background-color: #003087; /* Xavier blue */\n"
"}\n"
"QGroupBox {\n"
"    background-color: #003087;\n"
"    border: 2px solid #FFD700; /* Xavier gold border */\n"
"}\n"
"QGroupBox {\n"
"    background-color: #003087;\n"
"    border: 2px solid #FFD700;\n"
"    border-radius: 5px;\n"
"    color: white;\n"
"}")
        self.groupBox_4.setObjectName("groupBox_4")
        self.label_16 = QtWidgets.QLabel(parent=self.groupBox_4)
        self.label_16.setGeometry(QtCore.QRect(810, 10, 171, 141))
        self.label_16.setText("")
        self.label_16.setPixmap(QtGui.QPixmap("C:/Users/jhora/Downloads/XU_logo_type_ver_2.png"))
        self.label_16.setScaledContents(True)
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(parent=self.groupBox_4)
        self.label_17.setGeometry(QtCore.QRect(60, 60, 31, 31))
        self.label_17.setText("")
        self.label_17.setPixmap(QtGui.QPixmap("C:/Users/jhora/Downloads/2023_Facebook_icon.svg.png"))
        self.label_17.setScaledContents(True)
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(parent=self.groupBox_4)
        self.label_18.setGeometry(QtCore.QRect(110, 60, 41, 31))
        self.label_18.setText("")
        self.label_18.setPixmap(QtGui.QPixmap("C:/Users/jhora/Downloads/Logo_of_Twitter.svg.webp"))
        self.label_18.setScaledContents(True)
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(parent=self.groupBox_4)
        self.label_19.setGeometry(QtCore.QRect(160, 60, 31, 31))
        self.label_19.setText("")
        self.label_19.setPixmap(QtGui.QPixmap("C:/Users/jhora/Downloads/images (1).jpg"))
        self.label_19.setScaledContents(True)
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(parent=self.groupBox_4)
        self.label_20.setGeometry(QtCore.QRect(490, 40, 341, 61))
        self.label_20.setStyleSheet("QLabel {\n"
"    font-family: \"Times New Roman\";\n"
"    font-size: 10pt;\n"
"    font-weight: bold;\n"
"    color: #FFFFFF;\n"
"}")
        self.label_20.setObjectName("label_20")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1004, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "GroupBox"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Search..</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.groupBox_2.setTitle(_translate("MainWindow", "GroupBox"))
        self.toolButton.setText(_translate("MainWindow", "About"))
        self.toolButton_2.setText(_translate("MainWindow", "Centennial"))
        self.toolButton_3.setText(_translate("MainWindow", "Testing & Admissions"))
        self.toolButton_4.setText(_translate("MainWindow", "Scholarships"))
        self.toolButton_5.setText(_translate("MainWindow", "Enroll Now"))
        self.toolButton_6.setText(_translate("MainWindow", "Academics"))
        self.toolButton_7.setText(_translate("MainWindow", "Research"))
        self.toolButton_8.setText(_translate("MainWindow", "Presidents Memo"))
        self.toolButton_9.setText(_translate("MainWindow", "Contact Us"))
        self.groupBox_3.setTitle(_translate("MainWindow", "GroupBox"))
        self.label_6.setText(_translate("MainWindow", "Xavier Ateneo Spotlight"))
        self.label_10.setText(_translate("MainWindow", "Xavier Ateneo sets in motion site development"))
        self.label_11.setText(_translate("MainWindow", "highlighting eco-friendly features"))
        self.label_13.setText(_translate("MainWindow", "of the Campus of the feature"))
        self.label_14.setText(_translate("MainWindow", "College of Agriculture Farm Laboratory in El Gaucho"))
        self.label_15.setText(_translate("MainWindow", "XU Atiman Kinaiyahan: Tree Growing Program"))
        self.groupBox_4.setTitle(_translate("MainWindow", "GroupBox"))
        self.label_20.setText(_translate("MainWindow", "© 2025 Xavier University - Ateneo de Cagayan\n"
"Corrales Avenue, Cagayan de Oro City, Philippines"))
import sys
from PyQt6.QtWidgets import QApplication, QMainWindow

if __name__ == "__main__":
    app = QApplication(sys.argv)
    MainWindow = QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
